print("importing levels...")

level0 = [
            "WWSWWWWWWWWWWWWWWWWWWWWWWXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
            "W                                                                                      W",
            "W                                                                                      W",
            "W                                      PCP                                             W",
            "W                    PPPPPCPPPPP       P P                                             W",
            "W                    P         P                                                       W",
            "W                                                                                      W",
            "W                                                                                      W",
            "W    PPPPCPPPP                                                                         W",
            "W    P       P                                                                         W",
            "W                          PPPCPPP                                                     W",
            "W                          P     P                                                     W",
            "W                                                                                      W",
            "W                                                                                      W",
            "W                                                                                      W",
            "W                     PPPCPPP                        E                                 W",
            "W                     P     P                     PPCPP                                W",
            "W     PPPCPPP                                       B                                  W",
            "W     P     P                                       B             C                    W",
            "W                    PPPCPPP                        B       C     B                    W",
            "W                    P  B  P                        B       B     B                    W",
            "W                       B                           B       B     B                    W",
            "W                       B                           B       B     B                    X",
            "W                       B                 E         B       B     B        C       E   X",
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW       W WWWWWWWWWWW",
        ]

level1 = [
            "WWWWSWWWWWWWWWWWWWWWWWWWWXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
            "W                                                                                      W",
            "W                                        E                                             W",
            "W                        E             PCP                                             W",
            "W                    PPPPPCPPPPP       P P                                             W",
            "W                    P         P                                                       W",
            "W                                                                                      W",
            "W       E                                                                              W",
            "W    PPPPCPPPP                                                                         W",
            "W    P       P                  E                                                      W",
            "W                          PPPCPPP                                                     W",
            "W                          P     P                                                     W",
            "W                                                                                      W",
            "W                                                                                      W",
            "W                        E                                                             W",
            "W                     PPPCPPP                        E                                 W",
            "W        E            P     P                     PPCPP                                W",
            "W     PPPCPPP                                       B                                  W",
            "W     P     P           E                           B             C                    W",
            "W                    PPPCPPP                        B       C     B                    W",
            "W                    P  B  P                        B       B     B                    W",
            "W                       B                           B       B     B                    W",
            "W                       B                           B       B     B        E           X",
            "W       E               B            E    E         B       B     B        C       E   X",
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW       W WWWWWWWWWWW",
        ]

level2 = [
            "WWWWSWWWWWWWWWWWWWWWWWWWWXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
            "W                                                                                      W",
            "W                                        E                                             W",
            "W                        E             PCP                                             W",
            "W                    PPPPPCPPPPP       P P                                             W",
            "W                    P         P                                                       W",
            "W                                                                                      W",
            "W       E                                                                              W",
            "W    PPPPCPPPP                                                                         W",
            "W    P       P                  E                                                      W",
            "W                          PPPCPPP                                                     W",
            "W                          P     P                                                     W",
            "W                                                                                      W",
            "W                                                                                      W",
            "W                        E                                                             W",
            "W                     PPPCPPP                        E                                 W",
            "W        E            P     P                     PPCPP                                W",
            "W     PPPCPPP                                       B                                  W",
            "W     P     P           E                           B             C                    W",
            "W                    PPPCPPP                        B       C     B                    W",
            "W                    P  B  P                        B       B     B                    W",
            "W                       B                           B       B     B                    W",
            "W                       B                           B       B     B        E           X",
            "W       E               B            E    E         B       B     B        C       E   X",
            "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW       W WWWWWWWWWWW",
        ]